name: Playwright test
on: [push,pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup node.js
              uses: actions/setup-node@v3
            - name: Install dependencies
              run: npm install
            - name: Install Playwright browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test
              env:
                CI: 'true'
            - name: Upload test results
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30

